---
- name: Check Disk Space on Windows Server 2016 and Save to Network Share
  hosts: windows # Replace with your actual inventory group name
  gather_facts: yes
  tasks:
    - name: Get Hostname
      win_shell: hostname
      register: hostname_output

    - name: Set Hostname Variable
      set_fact:
        hostname: "{{ hostname_output.stdout.strip() }}"

    - name: Create temp directory on network share using PowerShell
      win_shell: |
        $path = '\\\\192.168.29.132\\Patches\\temp'
        if (-not (Test-Path -Path $path)) {
          New-Item -Path $path -ItemType Directory
        }
      register: create_temp_dir
      failed_when: create_temp_dir.rc != 0

    - name: Get Disk Space Information
      win_shell: |
        Get-PSDrive -PSProvider FileSystem |
        Select-Object Name,
          @{Name='Used_GB';Expression={[math]::Round($_.Used/1GB,2)}},
          @{Name='Free_GB';Expression={[math]::Round($_.Free/1GB,2)}},
          @{Name='Total_GB';Expression={[math]::Round($_.Size/1GB,2)}} |
        ConvertTo-Xml -As List -Depth 1
      register: disk_space_xml_raw
      failed_when: disk_space_xml_raw.rc != 0

    - name: Save Disk Space to XML File on Network Share
      win_copy:
        content: "{{ disk_space_xml_raw.stdout }}"
        dest: '\\\\192.168.29.132\\Patches\\temp\\{{ hostname }}_disk_space.xml'

    - name: Display Confirmation Message
      debug:
        msg: "Disk space information saved to \\\\192.168.29.132\\Patches\\temp\\{{ hostname }}_disk_space.xml"
