---
- name: Check Disk Space on Windows Server 2016
  hosts: windows # Replace with your actual inventory group name
  gather_facts: yes # Consider enabling facts if you might need them later
  tasks:
    - name: Ensure C:\temp directory exists
      win_file:
        path: C:\temp
        state: directory

    - name: Get Disk Space Information and Save to JSON
      win_shell: |
        Get-PSDrive -PSProvider FileSystem |
        Select-Object Name,
          @{Name='Used(GB)';Expression={[math]::Round($_.Used/1GB,2)}},
          @{Name='Free(GB)';Expression={[math]::Round($_.Free/1GB,2)}},
          @{Name='Total(GB)';Expression={[math]::Round($_.Size/1GB,2)}} |
        ConvertTo-Json
      register: disk_space_raw
      failed_when: disk_space_raw.rc != 0 # Fail the task if the command fails

    - name: Save Disk Space to JSON File
      win_copy:
        content: "{{ disk_space_raw.stdout }}"
        dest: C:\temp\disk_space.json

    - name: Display Disk Space
      debug:
        msg: "{{ disk_space_raw.stdout | from_json }}"
