---
- name: Install all available updates on Windows Server
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure C:\temp exists
      win_file:
        path: C:\temp
        state: directory

    - name: Install PSWindowsUpdate with NuGet fallback
      win_shell: |
        Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {
          Install-PackageProvider -Name NuGet -Force
        }
        if (-not (Get-Module -ListAvailable -Name PSWindowsUpdate)) {
          Install-Module -Name PSWindowsUpdate -Force
        }
        Import-Module PSWindowsUpdate
      args:
        executable: powershell.exe

    - name: Run Windows Update
      win_shell: |
        Get-WindowsUpdate -AcceptAll -Install -IgnoreReboot |
        Out-File -FilePath C:\temp\win_update_log.txt -Append
      args:
        executable: powershell.exe

    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 1800
