---
- name: Map Network Drive, Install Patch from Share, and Disconnect
  hosts: all
  gather_facts: yes
  vars:
    drive_letter: 'U:'
    share_path: '\\192.168.29.132\Patches'
  tasks:
    - name: Check if drive is already mapped
      win_command: |
        if (Get-PSDrive -Name {{ drive_letter }} -ErrorAction SilentlyContinue) {
          Write-Host "{{ drive_letter }} is already mapped"
          exit 0
        } else {
          Write-Host "{{ drive_letter }} is not mapped"
          exit 1
        }
      register: drive_check_result
      changed_when: false
      failed_when: drive_check_result.rc > 1

    - name: Map network drive
      win_command: |
        net use {{ drive_letter }} {{ share_path }} /persistent:yes
      register: map_drive_result
      ignore_errors: yes #to avoid  failure in case drive is already mapped
      become: yes
      become_method: runas
      become_user: system
      when: drive_check_result.rc == 1
    - name: Print map drive results
      debug:
        var: map_drive_result
      when: drive_check_result.rc == 1

    - name: Install hotfix from shared location
      community.windows.win_hotfix:
        source: "{{ drive_letter }}:\\KB5055521.msu"
        state: present
      when:
        - ansible_facts.os_name == "Microsoft Windows Server 2016 Standard"
      register: hotfix_install_2016
      become: yes
      become_method: runas
      become_user: system

    - name: Print hotfix installation result
      debug:
        var: hotfix_install_2016

    - name: Create log file
      win_shell: |
        $logPath = "C:\temp\patch_installation.log"
        "KB5055521 Installation Result: $($hotfix_install_2016)" | Out-File -FilePath $logPath -Append

        $rebootRequired = $false


        if ($hotfix_install_2016.reboot_required) {
            $rebootRequired = $true
            "KB5055521: Restart is needed" | Out-File -FilePath $logPath -Append
        }


        if ($rebootRequired -eq $true ) {
          "Reboot is required." | Out-File -FilePath $logPath -Append
        }
        else {
          "Reboot is not required." | Out-File -FilePath $logPath -Append
        }
      register: log_result
      become: yes
      become_method: runas
      become_user: system

    - name: Print log results
      debug:
        var: log_result
    - name: Reboot the server if required
      win_reboot:
      when: log_result.changed
      become: yes
      become_method: runas
      become_user: system
    - name: Disconnect the network drive
      win_command: |
        net use {{ drive_letter }} /delete
      ignore_errors: yes
      become: yes
      become_method: runas
      become_user: system
