---
- name: Install all Windows Updates on Windows Server
  hosts: windows
  gather_facts: no
  become: false

  tasks:

    - name: Ensure PSWindowsUpdate module is installed
      ansible.windows.win_shell: |
        Install-PackageProvider -Name NuGet -Force
        Install-Module -Name PSWindowsUpdate -Force -AllowClobber
      args:
        executable: powershell.exe

    - name: Create a scheduled task to run Windows Update as SYSTEM
      ansible.windows.win_scheduled_task:
        name: ForceWindowsUpdate
        description: Install all available updates automatically
        actions:
          - path: powershell.exe
            arguments: "-ExecutionPolicy Bypass -Command \"Import-Module PSWindowsUpdate; Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot | Tee-Object -FilePath 'C:\\Temp\\ForceUpdateLog.txt'\""
        triggers:
          - type: once
            start_boundary: "{{ lookup('pipe', \"powershell -Command \\\"(Get-Date).AddMinutes(1).ToString('yyyy-MM-ddTHH:mm:ss')\\\"\") }}"
        username: SYSTEM
        state: present

    - name: Run the scheduled task immediately
      ansible.windows.win_shell: |
        schtasks /Run /TN "ForceWindowsUpdate"
      args:
        executable: cmd.exe

    - name: Wait for updates to install (approx 20 minutes)
      ansible.builtin.pause:
        minutes: 20

    - name: Check if reboot is required
      ansible.windows.win_reboot:
        reboot_timeout: 3600
        test_command: 'powershell -Command "(Get-WmiObject -Class Win32_OperatingSystem).RebootRequired -eq $true"'
      register: reboot_result
      ignore_errors: true

    - name: Reboot the server if required
      ansible.windows.win_reboot:
        reboot_timeout: 3600
      when: reboot_result.changed

    - name: Delete the scheduled task
      ansible.windows.win_scheduled_task:
        name: ForceWindowsUpdate
        state: absent

