---
- name: Windows 2019 Server Patch Management
  hosts: your_windows_host  # Replace with your actual host or group
  gather_facts: no
  collections:
    - ansible.windows
  tasks:

    - name: Ensure C:\Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Install PSWindowsUpdate module if not already installed
      win_shell: |
        if (-not (Get-Module -ListAvailable -Name PSWindowsUpdate)) {
            Install-Module -Name PSWindowsUpdate -Force -Scope AllUsers
        }
      args:
        executable: powershell.exe

    - name: Trigger Windows Update - Install all available updates
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot -Verbose | Tee-Object -FilePath "C:\Temp\WindowsUpdateInstallLog.txt"
      args:
        executable: powershell.exe
      register: windows_update_result
      ignore_errors: yes

    - name: Reboot if updates required
      win_reboot:
        reboot_timeout: 1800
      when: windows_update_result.changed

    - name: Gather installed patches after update
      win_command: powershell.exe -Command "Get-HotFix | Select-Object -Property Description,HotFixID,InstalledOn | Format-Table -AutoSize"
      register: installed_patches

    - name: Write installed patches to a log file
      win_copy:
        content: |
          Installed Patches as of {{ ansible_date_time.date }} {{ ansible_date_time.time }}

          {% for line in installed_patches.stdout_lines %}
          {{ line }}
          {% endfor %}
        dest: C:\Temp\InstalledPatchesLog.txt

    - name: Display installed patches
      debug:
        var: installed_patches.stdout_lines
