---
- name: Manage Windows Server 2016
  hosts: your_windows_host  # <-- Replace with your host or group name
  gather_facts: yes
  tasks:

    - name: Ensure WinRM service is running
      win_service:
        name: WinRM
        state: started

    - name: Gather WinRM service facts
      win_service_facts:

    - name: Display WinRM service status
      debug:
        var: ansible_facts.services.WinRM.state

    - name: Ensure PSWindowsUpdate Module is installed
      win_shell: |
        if (-not (Get-Module -ListAvailable -Name PSWindowsUpdate)) {
          Install-PackageProvider -Name NuGet -Force
          Install-Module -Name PSWindowsUpdate -Force
        }
      register: pswindowsupdate_install
      ignore_errors: yes

    - name: Log PSWindowsUpdate Module installation result
      debug:
        var: pswindowsupdate_install.stdout_lines

    - name: Run Windows Update (Force Fresh Download)
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot | Tee-Object -FilePath "C:\\Temp\\ForceUpdateLog.txt"
      register: update_result
      ignore_errors: yes

    - name: Log Update Result
      debug:
        var: update_result

    - name: Reboot system if required after updates
      win_reboot:
        reboot_timeout: 600
      when: update_result.changed

    - name: Re-run Windows Update if new updates are found after reboot
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot | Tee-Object -FilePath "C:\\Temp\\ForceUpdateLog_SecondRun.txt"
      when: update_result.changed
      register: second_update_result
      ignore_errors: yes

    - name: Log Second Update Result
      debug:
        var: second_update_result

    - name: Verify updates installed correctly
      win_shell: |
        Get-HotFix
      register: installed_hotfixes

    - name: Display Installed Updates
      debug:
        var: installed_hotfixes.stdout_lines
