---
- name: Manually Check and Install Security and Critical Updates on Windows Server 2019
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure WinRM service is running
      win_service:
        name: WinRM
        state: started
        start_mode: auto

    - name: Start Windows Update service
      win_service:
        name: wuauserv
        state: started
        start_mode: auto

    - name: Create Log Directory
      win_file:
        path: C:\temp
        state: directory

    - name: Manually Check for Security and Critical Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: search_result
      ignore_errors: yes

    - name: Debug - Show Number of Updates Found
      debug:
        msg: "Updates found: {{ search_result.found_update_count }}"
      when: search_result.found_update_count is defined

    - name: Log Search Summary
      win_shell: |
        "$((Get-Date).ToString()) - [Win2019] Update Check Completed. Updates Found: {{ search_result.found_update_count }}" | Out-File -FilePath C:\temp\update_check.log -Append
      when: search_result.found_update_count is defined

    - name: Log Found Update Titles
      win_shell: |
        "$((Get-Date).ToString()) - [Win2019] Found Update: {{ item.value.title }}" | Out-File -FilePath C:\temp\update_check.log -Append
      loop: "{{ search_result.updates | dict2items }}"
      when: search_result.updates is defined and search_result.found_update_count | int > 0

    - name: Install Security and Critical Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: no
      when: search_result.found_update_count | int > 0
      register: update_result
      ignore_errors: yes

    - name: Log Successfully Installed Updates
      win_shell: |
        "$((Get-Date).ToString()) - [Win2019] Installed Successfully: {{ item.value.title }}" | Out-File -FilePath C:\temp\update_install.log -Append
      loop: "{{ update_result.updates | dict2items }}"
      when: item.value.result == 'Succeeded'

    - name: Log Failed Updates
      win_shell: |
        "$((Get-Date).ToString()) - [Win2019] Failed to Install: {{ item.value.title }}" | Out-File -FilePath C:\temp\update_install.log -Append
      loop: "{{ update_result.updates | dict2items }}"
      when: item.value.result == 'Failed'

    - name: Log Errors if Update Fails
      win_shell: |
        "$((Get-Date).ToString()) - [Win2019] Windows Update Error: {{ update_result.msg }}" | Out-File -FilePath C:\temp\update_errors.log -Append
      when: update_result.failed_update_count > 0

    - name: Reboot if Updates Require It
      win_reboot:
        reboot_timeout: 3600
      when: update_result.reboot_required
