    - name: Create a one-time scheduled task to run Windows Update
      ansible.windows.win_scheduled_task:
        name: RunPSWindowsUpdate
        description: Installs all updates via PSWindowsUpdate module
        actions:
          - path: powershell.exe
            arguments: >
              -ExecutionPolicy Bypass -WindowStyle Hidden -Command "Import-Module PSWindowsUpdate;
              Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot |
              Tee-Object -FilePath 'C:\Temp\ForceUpdateLog.txt'"
        triggers:
          - type: once
            start_boundary: "{{ (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') + timedelta(minutes=1)).isoformat() }}"
        username: SYSTEM
        run_level: highest
        state: present

    - name: Run the scheduled update task immediately
      ansible.windows.win_shell: schtasks /run /tn RunPSWindowsUpdate

    - name: Wait 5 minutes for update task to run
      ansible.builtin.pause:
        minutes: 5

    - name: Reboot if required
      ansible.windows.win_reboot:
        reboot_timeout: 3600
