---
- name: Install All Available Updates on Windows Server 2019
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure WinRM service is running
      win_service:
        name: WinRM
        state: started
        start_mode: auto

    - name: Start Windows Update service
      win_service:
        name: wuauserv
        state: started
        start_mode: auto

    - name: Create Log Directory
      win_file:
        path: C:\temp
        state: directory

    - name: Install All Available Windows Updates
      win_updates:
        # No category_names filter = install all available updates
        reboot: no
        state: installed
      register: update_result
      ignore_errors: yes

    - name: Log Installed Updates
      win_shell: |
        "$((Get-Date).ToString()) - Installed: {{ item.value.title }} (KB{{ item.value.kb[0] | default('N/A') }}) - Status: {{ 'Success' if item.value.installed else 'FAILED' }}" | Out-File -FilePath C:\temp\update_install.log -Append
      loop: "{{ update_result.updates | dict2items }}"
      when: update_result.updates is defined

    - name: Log Update Errors
      win_shell: |
        "$((Get-Date).ToString()) - Windows Update Error: {{ update_result.msg | default('No detailed error') }}" | Out-File -FilePath C:\temp\update_errors.log -Append
      when: update_result.failed_update_count | default(0) | int > 0

    - name: Reboot if Required After Updates
      win_reboot:
        reboot_timeout: 3600
      when: update_result.reboot_required | default(false)
