---
- name: Windows Server Management Playbook
  hosts: your_windows_host  # Replace with your Windows host or IP address
  gather_facts: yes
  collections:
    - ansible.windows
  tasks:

    # Ensure WinRM service is running
    - name: Ensure WinRM service is running
      win_service:
        name: WinRM
        state: started

    # Gather facts about the Windows services
    - name: Gather WinRM service facts
      win_service_info:
        name: WinRM
      register: winrm_service_info

    # Display the status of WinRM service
    - name: Display WinRM service status
      debug:
        var: winrm_service_info.services[0].state

    # Run Windows Update and ensure all available updates are installed
    - name: Run Windows Update (Force Fresh Download)
      win_command: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot | Tee-Object -FilePath "C:\\Temp\\ForceUpdateLog.txt"
      register: update_result
      ignore_errors: yes

    # Log the update result
    - name: Log Update Result
      debug:
        var: update_result

    # Reboot if necessary after update installation
    - name: Reboot system if required after updates
      win_reboot:
        reboot_timeout: 600
      when: update_result.changed

    # Install all missing updates after reboot (if necessary)
    - name: Re-run Windows Update if new updates are found after reboot
      win_command: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot | Tee-Object -FilePath "C:\\Temp\\ForceUpdateLog_SecondRun.txt"
      when: update_result.changed
      register: second_update_result
      ignore_errors: yes

    # Log the second update result after reboot
    - name: Log Second Update Result
      debug:
        var: second_update_result

    # Ensure the updates are installed properly
    - name: Verify updates installed correctly
      win_command: |
        Get-HotFix
      register: installed_hotfixes

    # Display the list of installed updates
    - name: Display Installed Updates
      debug:
        var: installed_hotfixes.stdout_lines
