---
- name: Fully Patch Windows Server 2019 (Clean + Reliable)
  hosts: all
  gather_facts: no

  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Stop Windows Update Services (Before Clearing Cache)
      win_shell: |
        net stop wuauserv
        net stop bits
      args:
        executable: powershell.exe
      ignore_errors: yes

    - name: Clear Windows Update Cache
      win_shell: |
        Remove-Item -Path "C:\Windows\SoftwareDistribution\*" -Recurse -Force
      args:
        executable: powershell.exe
      ignore_errors: yes

    - name: Start Windows Update Services (After Cache Clear)
      win_shell: |
        net start wuauserv
        net start bits
      args:
        executable: powershell.exe
      ignore_errors: yes

    - name: Install NuGet Provider (Required for PSWindowsUpdate)
      win_shell: |
        Install-PackageProvider -Name NuGet -Force
      args:
        executable: powershell.exe

    - name: Install PSWindowsUpdate Module
      win_shell: |
        Install-Module -Name PSWindowsUpdate -Force -Confirm:$false
      args:
        executable: powershell.exe

    - name: Import PSWindowsUpdate Module
      win_shell: |
        Import-Module PSWindowsUpdate
      args:
        executable: powershell.exe

    - name: Run Windows Update (Force Fresh Download)
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -ForceDownload -IgnoreReboot | Tee-Object -FilePath "C:\Temp\ForceUpdateLog.txt"
      args:
        executable: powershell.exe
      register: update_output

    - name: Reboot if required (safety net)
      win_reboot:
        reboot_timeout: 3600
