---
- name: Manage Windows Updates on Windows Server 2016
  hosts: WIN2016DC
  gather_facts: no
  tasks:
    - name: Start Windows Update service if disabled
      win_service:
        name: wuauserv
        state: started
        start_mode: auto

    - name: Check for Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
