---
- name: Install all available updates and reboot Windows Server 2016
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Ensure WinRM or SSH is configured
      win_ping:

    - name: Check and install all available updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        reboot: yes
      register: update_result

    - name: Display update results
      debug:
        var: update_result
