- name: Enable, Start, Check, and Install Windows Updates
  hosts: windows
  tasks:
    - name: Ensure Windows Update Service is Enabled
      win_service:
        name: wuauserv
        start_mode: auto

    - name: Start Windows Update Service
      win_service:
        name: wuauserv
        state: started

    - name: Check for Available Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: update_result

    - name: Display Available Updates
      debug:
        var: update_result.updates

    - name: Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: install_result

    - name: Display Installed Updates
      debug:
        var: install_result.installed_updates
