---
- name: Start patch installation on Windows Server 2016
  hosts: 192.168.29.155
  gather_facts: no
  tasks:
    - name: Ensure WinRM or SSH is configured
      win_ping:

    - name: Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result

    - name: Display update results
      debug:
        var: update_result
