- name: Manage Windows Updates
  hosts: windows
  tasks:
    - name: Start Windows Update Service
      win_service:
        name: wuauserv
        state: started

    - name: Search for available updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: update_result

    - name: Display available updates
      debug:
        var: update_result.updates
