---
- hosts: windows-machines
  vars_files:
   - /etc/ansible/group_vars/vault.yml
  vars:
    win_updates_categories:
     - CriticalUpdates
     - SecurityUpdates
     - Updates
  tasks:
  - name: checking for missing updates
    win_updates:
     state: installed
     category_names: "{{ win_updates_categories }}"
     register: update_count
