---
- hosts: windows_servers
  gather_facts: false
  become: yes
  become_method: runas
  become_user: Ansible
  tasks:
    - name: Ensure C:\temp directory exists
      ansible.windows.win_file:
        path: C:\temp
        state: directory
        mode: 0777

    - name: Install all available Windows updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - FeaturePacks
          - ProductUpdates
          - UpdateRollups
          - DefinitionUpdates
          - Others
        log_path: C:\temp\windows_update_log.txt
        reboot: yes
        async: 1000
        poll_interval: 10
