---
- name: Connect to Windows 2016 Server via SSH
  hosts: 192.168.29.155
  gather_facts: no
  tasks:
    - name: Check SSH connectivity
      ansible.builtin.command: "whoami"
      register: ssh_result
      ignore_errors: yes

    - name: Log success
      ansible.builtin.lineinfile:
        path: "/var/log/ansible/windows_ssh_log.txt"
        line: "SUCCESS: {{ inventory_hostname }} connected successfully as {{ ssh_result.stdout }}"
        create: yes
      when: ssh_result.rc == 0

    - name: Log failure
      ansible.builtin.lineinfile:
        path: "/var/log/ansible/windows_ssh_log.txt"
        line: "FAILURE: {{ inventory_hostname }} connection failed - {{ ssh_result.stderr }}"
        create: yes
      when: ssh_result.rc != 0
