- name: Create a file in C:\Temp on Windows Server
  hosts: windows
  tasks:
    - name: Ensure C:\Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Create a file in C:\Temp
      win_file:
        path: C:\Temp\example.txt
        state: touch
