- name: Enable, Start Windows Update Service, Check for Updates, and Install All Available Updates
  hosts: windows
  tasks:
    - name: Ensure Windows Update Service is Enabled
      win_service:
        name: wuauserv
        start_mode: auto

    - name: Start Windows Update Service
      win_service:
        name: wuauserv
        state: started

    - name: Install PSWindowsUpdate Module (if not installed)
      win_shell: |
        if (-not (Get-Module -ListAvailable -Name PSWindowsUpdate)) {
            Install-Module -Name PSWindowsUpdate -Force -SkipPublisherCheck
        }
      args:
        executable: powershell.exe

    - name: Check for All Available Windows Updates
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WUList | Format-Table -AutoSize
      args:
        executable: powershell.exe
      register: update_check_result

    - name: Display Available Updates
      debug:
        var: update_check_result.stdout_lines

    - name: Install All Available Windows Updates Immediately
      win_shell: |
        Import-Module PSWindowsUpdate
        Install-WindowsUpdate -AcceptAll -IgnoreReboot -AutoReboot
      args:
        executable: powershell.exe
      register: install_result
      changed_when: "'Installing updates' in install_result.stdout"

    - name: Display Installed Updates
      debug:
        var: install_result.stdout_lines
