---
- name: Check and Install Updates on Windows Server 2016
  hosts: Win2016Client1
  gather_facts: no
  tasks:
    - name: Ensure WinRM service is running
      win_service:
        name: WinRM
        state: started
        start_mode: auto

    - name: Start Windows Update service if disabled
      win_service:
        name: wuauserv
        state: started
        start_mode: auto

    - name: Check for and Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
